<tr>
    <td>${hourly.time}</td>
    <td>${hourly.tempC}</td>
    <td>${hourly.rainChance}</td>
    <td>${hourly.cloud}</td>
    <td>${hourly.hum}</td>
    <td>${hourly.pres}</td>
    <td>${hourly.precip}</td>
    <td>${hourly.windMs}</td>
</tr>